language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install numpy scipy"
  - "pip install pytest"
  - "pip install cython"

# command to run tests
script:
  - pytest
  - python setup.py build_ext

branches:
    only:
        - master

notifications:
    email: false